### PR TITLE
JavaDoc and Lint

### PR DESCRIPTION
**Pull request by boorac**
# Motivation
I am planning to use your simulator to simulate some work of my own. In my attempt to understand the code base I decided to lint it and add JavaDocs. I added a linter config and rewrote the majority of the project. Some unknowns and improvement suggestions have been marked with TODOS.

All changes are safe, meaning only formatting and editor refactors have been applied.

## Changes Summary

1. added gitignore for intellijIDEA
2. linted code to conform to Checkstyle 8.32 Google Checks, `google-checks.xml` Checkstyle config is provided
3. code that was deemed to hard to rewrite without introducing bugs was ignored using ` checkstyle-suppressions.xml `
4. Renamed some variables to add semantic meaning
5. Added TODOs where improvements are possible and where I did not understand the logic
6. Shortened some expressions, removed IDE warnings
 
## Future changes
In my second iteration, I would like to rewrite some parts to improve the code base - these changes might not be safe. Thank you for this open source simulator :tada:

### CODE REVIEW

**Comment by themattman18** [comment]
I've made several documentation changes as well but I'll wait to issue a pull request until I get these changes. What are looking to add to the simulator?

**Comment by boorac** [comment]
@themattman18 currently I am just trying to map out the network topology and confirm that it corresponds to the findings reported in:

>  Andrew Miller, James Litton, Andrew Pachulski, Neal Gupta, Dave Levin, Neil Spring, and Bobby Bhattacharjee. Discovering bitcoins public topology and influential nodes. 2015.

That paper is referenced by the paper published along with the simulator source:

> SimBlock: A Blockchain Network Simulator Yusuke Aoki, Kai Otsuki, Takeshi Kaneko, Ryohei Banno and Kazuyuki Shudo  Tokyo Institute of Technology 2-12-1 Ookayama, Meguro-ku, Tokyo, Japan Email: {aoki.y.au, ootuki.k.aa, kaneko.t.ay}@m.titech.ac.jp, banno@computer.org, shudo@is.titech.ac.jp arXiv:1901.09777v2

What I am still trying to grasp are the constants DEGREE_DISTRIBUTION_*, as defined in: https://github.com/dsg-titech/simblock/blob/a862b57189fe591e1876a2c063eaef5848cafa0c/simulator/src/main/java/SimBlock/settings/NetworkConfiguration.java#L68

I have tried contacting the authors via googlegroups.com but no luck... I will try to contact them via email.

For what are you using the simulator? Would you be interested in maintaining a fork of this repo (I plan on maintaining my fork, since it seems this one is no longer maintained)?

**Comment by themattman18** [comment]
I would be interested in maintaining a fork. I've added support for simulating selfish mining which I'm looking to get published. I'd like to add automated tests that verify any future changes to the program still conform to the parameters the authors referenced in their paper. I've changed a lot of the structure around [Node.java](https://github.com/themattman18/simblock/blob/SelfishMining/simulator/src/main/java/SimBlock/node/Node.java) by making it implement an interface. My changes were pretty extensive so I'll get yours first and merge them into mine

**Comment by boorac** [comment]
That is great news! I suggest we continue this discussion elsewhere. Could you contact me on `fmbencic@gmail.com` so we can agree upon a communication channel?

**Comment by nabon** [comment]
Thank you for your useful update on SimBlock, and sorry for the very late reply.
We've confirmed that the changes are safe.

There is one minor thing.

https://github.com/dsg-titech/simblock/blob/9ba57fe7f03e816091c45535c5e6e4ab4eb5ecbd/simulator/src/main/java/simblock/block/Block.java#L45-L48

`Node unique id` should be changed to `Block unique id`.

After you fix the above, I will merge this PR.
We deeply appreciate your contribution to SimBlock.

The following are answering some of your questions stated as TODOs.

---

https://github.com/dsg-titech/simblock/blob/9ba57fe7f03e816091c45535c5e6e4ab4eb5ecbd/simulator/src/main/java/simblock/block/Block.java#L104-L107
`getTime()` returns the timestamp which is the elapsed time from the beginning of the simulation in milliseconds.

---

https://github.com/dsg-titech/simblock/blob/9ba57fe7f03e816091c45535c5e6e4ab4eb5ecbd/simulator/src/main/java/simblock/simulator/Main.java#L257
`facum` indicates whether the distribution is an accumulative (cumulative) function or not.
I found that we made some typos: "acumulative" must be "accumulative".

---

https://github.com/dsg-titech/simblock/blob/9ba57fe7f03e816091c45535c5e6e4ab4eb5ecbd/simulator/src/main/java/simblock/simulator/Timer.java#L47-L48
`currentTime` is in milliseconds.

---

https://github.com/dsg-titech/simblock/blob/9ba57fe7f03e816091c45535c5e6e4ab4eb5ecbd/simulator/src/main/java/simblock/task/MiningTask.java#L38-L39
The parameter `difficulty` is used to calculate the required time for mining.
The calculation is done in:

https://github.com/dsg-titech/simblock/blob/9ba57fe7f03e816091c45535c5e6e4ab4eb5ecbd/simulator/src/main/java/simblock/node/consensus/ProofOfWork.java#L49-L52
https://github.com/dsg-titech/simblock/blob/9ba57fe7f03e816091c45535c5e6e4ab4eb5ecbd/simulator/src/main/java/simblock/node/consensus/SampleProofOfStake.java#L45-L50

The calculation is according to the following expression:

requiredTime = (log(u) / log(1 - 1/difficulty)) / miningPower

where,
- u: An uniform random number.
- difficulty: The number of hash calculations required to achieve the success of mining.
- miningPower: The number of mining (hash calculation) executed per millisecond.

The above expression generates a random number with geometric distribution by using inverse transform sampling.

**Comment by boorac** [comment]
@nabon - thank you for your feedback. The mistake has been corrected in the latest commit. I plan on resolving the TODOS in another MR. 

Could you maybe help me with the DEGREE_DISTRIBUTION_* constants as explained above?
Also, if you still plan on maintaining the project, we (as in @themattman18 and me) would like to continue contributing.

**Comment by nabon** [comment]
Thank you for the correction! I merged the PR.
Our research group is still working on blockchain techniques and we intend to continue maintaining SimBlock.
We're grateful for your planning for the improvement of SimBlock.

Regarding the parameter DEGREE_DISTRIBUTION_*, I'm uncertain how they were derived.
I’m sorry that I could not be of help to you.
If we get any additional information, we will update the documentation.

**Pull request merged**
